--READ UNCOMMITED

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT * FROM ShopSchema.Card WHERE cardID = 0

--READ COMMITED

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SELECT * FROM ShopSchema.Card WHERE cardID = 0

--REPEATABLE READ

UPDATE ShopSchema.Card SET phone = '89764489146' where cardID = 0
SELECT * FROM ShopSchema.Card WHERE cardID = 0

--SERIALIZABLE
INSERT INTO ShopSchema.Card (phone, firstName, lastName) VALUES ('88464423167', 'a', 'b')
