INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '512 Slim Taper Fit Stretch Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '502 Regular Taper Fit Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '511 Slim Fit Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '501 Original Fit Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '512 Original Fit Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '501 Taper Fit Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '511 Skinny Stretch Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '527 Slim Boot Cut Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '501 Taper Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '501 Original Fit Cool Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '504 Regular Straight Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Line 8 Slim Straight Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '504 Regular Straight Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '512 Slim Taper Fit Warp Stretch Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '511 Slim Fit Stretch Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '501 CT Jeans', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '501 Original Fit Pants', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( '511 Slim Fit Trousers', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Levi''s Graphic Tee', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Levi''s Housemark Tee', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Graphic Sport Logo Hoodies', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Graphic Crew Fleece', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'The Sherpa Trucker Jacket', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'The Trucker Jacket', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Down Davidson Parka', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Thermore Utility Coat', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'NY Runner II Sneaker', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Murphy Mid Boot', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Perris Oxford', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Premium Leather Icon Belt', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'Sonny Belt', 'Live in Levi''s', 'Turkey')
INSERT INTO ShopDB.ShopSchema.Item (itemName, description, country) VALUES ( 'California Embossed Indigo Belt', 'Live in Levi''s', 'Turkey')
